### ISSUE TITLE
Failed to load page with 404 when SSG

### ISSUE THREAD

**Issue by jill64** [jill64/sveltekit-adapter-aws#542]
related #540

Does not occur in CSR & `/sverdle`

| arch | result |
| - | - |
| lambda-s3 | NG |
| lambda-mono | NG |
| lambda-mono (with cdn) | NG |
| edge-bundled | NG |
| edge-unbundled | NG |

## repro

same #540

```
2024-03-31T01:06:59.833Z	d8ae34fa-7e97-4838-b1f4-40284593a371	ERROR	F [Error]: Not found: /
    at y (/var/task/server.js:148:17058)
    at resolve (/var/task/server.js:148:14893)
    at #e.hooks.handle (/var/task/server.js:148:18288)
    at ei (/var/task/server.js:148:14862) {
  status: 404,
  text: 'Not Found'
}
```

**Comment by jill64** [comment]
This seems to only occur during pre-rendering.
